### ISSUE TITLE
rebrand: Pagina de Contato

### ISSUE THREAD

**Issue by alexandrevicenzi** [HackerspaceBlumenau/hackerspaceblumenau.github.io#14]
Criar página contento informações de contato, de todos os meios possível.

Contatos:

- Email
- Slack
- Twitter
- Facebook
- Grupo do Telegram

o @jaswdr pode ajudar com esses detalhes e onde conseguir as info.

**Comment by ejulio** [comment]
Podem ser apenas links na home page :)

**Comment by alexandrevicenzi** [comment]
@ejulio se nao for ter form de contato pode ser no rodapé mesmo essas info, ai fica em todas paginas xD
