### ISSUE TITLE
rebrand: Página de Apoio/Patrocinio

### ISSUE THREAD

**Issue by alexandrevicenzi** [HackerspaceBlumenau/hackerspaceblumenau.github.io#15]
Criar página que contenha os apoiadores oficiais do HSBNU com imagem da logo e link para o site da empresa.

O @jaswdr pode ajudar com os apoiadores oficiais, que não são muitos.

Essa página não é para apoiadores de eventos ou similares, mas sim quem apoia o HSBNU de alguma forma frequentemente.

**Comment by ejulio** [comment]
Não sei se temos isso de fato.
A FURB apoia, mas não sei se faz sentido colocar isso lá (já fica claro pelos locais de meetup).
Assim como não sei se é muito válido aquele texto sobre "ajuda para um espaço", já conversei com um amigo meu e ele diz que isso é um anti-patter de hacler spaces

**Comment by alexandrevicenzi** [comment]
@ejulio isso podemos negociar, é que no site atual tem isso.
