### ISSUE TITLE
rebrand: Pagina de Fotos/Album

### ISSUE THREAD

**Issue by alexandrevicenzi** [HackerspaceBlumenau/hackerspaceblumenau.github.io#16]
O HSBNU mantém as fotos dos eventos no seu GDrive, seria interessante linkar de alguma forma o Drive nessa página para que as pessoas consigam baixar ou vizualizar as fotos.

Se for possivel fazer algum tipo de embed do Google Photos seria bom, caso contrário um link e algumas fotos exemplos já é o suficiente.

Olhando por cima é necessário incluir um link para cada álbum. Não existe embed oficial porém existe alguns sites que geram embed, algo um tanto desaconselhavel, pois já basta o Google ter acesso as images.

O @jaswdr e @jvanz possuem acesso ao Drive e podem ajudar a obter os links.

**Comment by jvanz** [comment]
Atualmente a maioria das fotos dos encontros regulares fica no meetup. Pois existe um bot que faz a divulgação automática com as fotos que são colocadas lá. Essas mesmas fotos estão nos aparelhos de quem tirou elas, geralmente eu ou o @ejulio . Se for criar algum algum, precisamos procurar por elas em nossos respectivos aparelhos.

**Comment by alexandrevicenzi** [comment]
@jvanz já temos albuns com varias fotos de vários eventos, bastaria fazer upload dessas demais que não estão, também não é necessário estar toda foto tirada, creio que ideal é mais fotos de eventos, os meetups semanais/mensais nem tanto assim, mas seria legal.

**Comment by ejulio** [comment]
Acho que é válido.
Só não sei se iria pirar muito em uma página para isso.
Podemos colocar o link para o album no photos e sempre tem em cada meetup o registro.
As principais poderiam ficar em um slideshow na página inicial, se assim fosse necessário
