### ISSUE TITLE
rebrand: Tema para o Hugo

### ISSUE THREAD

**Issue by alexandrevicenzi** [HackerspaceBlumenau/hackerspaceblumenau.github.io#19]
É necessário escolher/criar um tema para o HSBNU, com cores, logos, fontes especificas.

Existem alguns temas que podem ser adaptados (fork):

https://themes.gohugo.io/hugo-terrassa-theme/
https://themes.gohugo.io/devfest-theme-hugo/
https://themes.gohugo.io/kross-hugo-portfolio-template/
https://themes.gohugo.io/hugo-fresh/

**Comment by alexandrevicenzi** [comment]
Se for criar um tema novo o ideal é fazer um repositorio a parte, assim demais pessoas podem utilizá-lo.

**Comment by ejulio** [comment]
Só a logo, pequeno texto sobre e links para os demais serviços
https://themes.gohugo.io/theme/pulp/
