### ISSUE TITLE
rebrand: Pagina de Comunidades

### ISSUE THREAD

**Issue by alexandrevicenzi** [HackerspaceBlumenau/hackerspaceblumenau.github.io#20]
O HSBNU abraça várias comunidades e coordena algumas. Seria interessante incluir as comunidades em uma página, com respectivos logos, contatos, meetup ou meio de comunicação.

**Comment by ejulio** [comment]
Acho que é mais um ponto de encontro do que coordenar.
A ideia é que elas são independentes mas se encontram ali como um lugar comum.
É mais algo no sentido de parceria do que o HS acima dessas comunidades

**Comment by alexandrevicenzi** [comment]
@ejulio sim, de fato, mas seria legal ter uma pagina onde pode-se encontrar todas comunidades, nao estou fizendo que o HSBNU manda nelas, mas compartilhamos interesses, são bem poucas que são tocadas pelo HSBNU mesmo.
