### ISSUE TITLE
Link para ingressar no Slack expirou

### ISSUE THREAD

**Issue by jjpaulo2** [HackerspaceBlumenau/hackerspaceblumenau.github.io#41]
O link para o Slack, definido no arquivo [content/slack.md](https://github.com/HackerspaceBlumenau/hackerspaceblumenau.github.io/blob/master/content/slack.md) não está mais funcionando.

![image](https://github.com/HackerspaceBlumenau/hackerspaceblumenau.github.io/assets/22819523/5794b55a-cebf-4fc3-8540-adf81565e2c8)

**Comment by jjpaulo2** [comment]
@rtancman pelo que eu vi, o antigo formulário foi substituído só por um link de convite, que expirou.
 Só precisa gerar esse link novamente. Sabe quem consegue ajudar nisso?

**Comment by alexandrevicenzi** [comment]
@jjpaulo2 acho que apenas os admin podem gerar um link.

**Comment by alexandrevicenzi** [comment]
Tentei gerar um link, eles expiram em 30 dias a principio, meio inviavel usar esse metodo.

**Comment by alexandrevicenzi** [comment]
> For security reasons, links must expire. A link can be shared with up to 400 people.

Atualizei o link, mas em algum momento irá expirar de novo.

**Comment by jjpaulo2** [comment]
@alexandrevicenzi dá pra gerar esse link com a API do Slack.

https://api.slack.com/methods/admin.users.invite

Será se conseguimos fazer um app e rodar ele num fly.io da vida, ou OCI free tier?
Posso ajudar a construir! 😄

**Comment by jjpaulo2** [comment]
@alexandrevicenzi vi que já usavam um app assim, mas arquivaram o repo.

https://github.com/HackerspaceBlumenau/slackin

Por que fizeram isso? Só por causa do fim do Heroku free? Se for isso, podemos só fazer deploy no fly.io que é bem parecido.

**Comment by alexandrevicenzi** [comment]
@jjpaulo2 sim, pois o heroku deixou de ser free e pelo fato que era outro app pra manter.

A princípio o link atual irá expirar em alguns anos, e não 30 dias, o que é aceitável.

**Comment by jjpaulo2** [comment]
Ah, blz então. Valeu 😉
