### ISSUE TITLE
Capybara logo

### ISSUE THREAD

**Issue by vilanz** [HackerspaceBlumenau/hackerspaceblumenau.github.io#6]
Why is the German capybara not used anywhere in the site? I dig the "hackerman" look, but a cute capybara will certainly spice it up.

I might submit a PR or something, but I couldn't't find a high-resolution version.

**Comment by jaswdr** [comment]
@ludvon totally agree, did you can send some PR ? I'll analyse it and accept if everything is ok

**Comment by vilanz** [comment]
@jaswdr Is there a high-res version of the logo?

**Comment by jaswdr** [comment]
@ludvon yep, we have a dedicated repository for the logos, see [here](https://github.com/HackerspaceBlumenau/logos)

**Comment by vilanz** [comment]
@jaswdr Thanks and sorry!
